
services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: