
services:
  app:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 4000:3001
    depends_on:
      - mongodb
    image: dmf5969/cmpsc421_lab3:latest

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_URL="mongodb://mongodb:27017/database"
volumes:
  mongo-data: